### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by przemyslawpluta** [darsain/fs-extended#1]
Assuming:

``` js
function map(itemPath, stat) {
    return {
        path: itemPath,
        name: path.basename(itemPath),
        ext: path.extname(itemPath)
    };
}

fs.listAll(dir, { map: map }, function (err, files) {
    console.log(err);   // possible exception
    console.log(files); // array of file object descriptors returned by map()
    // Example
    files[0].path; // 1st file's path
    files[0].ext;  // 1st file's extension
});
```

Is there a way to get the list of all the files without fs.stat being performed on each file? Thanks.

**Comment by darsain** [comment]
Yah. Remove the `stat` argument from your `map()` function.

You can see the boolean that determines when stats object will be loaded on [line 1147](https://github.com/darsain/fs-extended/blob/a8dc9b29a40c29dfa49f115c109a262aea3dcf0d/index.js#L1147).

**Comment by przemyslawpluta** [comment]
Thank you.
