### ISSUE TITLE
fs-extended no results

### ISSUE THREAD

**Issue by przemyslawpluta** [darsain/fs-extended#2]
I have quite a massive directory with 30k files in it. And it looks like fs-extended is unable to return any list of the files from the directory. Is there a way to filter directory by mtime so only files created in the latest 24h / 48h will be listed? In theory this could limit that amount to >2000 files ...

**Comment by darsain** [comment]
Retrieving a list of 30k files takes quite some time. Are you sure you gave it enough of it? May be even minutes.

If your directory structure is just a shallow dir with files in it, the fastest way how to get list of them is calling `listAll()` without recursion enabled, and not accepting `stat` argument in filter or map functions. In this case fs-extended will only query all files in the directory, which is quite fast.

If you need recursive list, or you need to map and or filter based on `stat` object, fs-extended has to get the `stat` object for each item in the directory, which takes a lot of time.

If you want to process files as they are being read from filesystem (and not wait for the whole list to load before you can do something), you should look for a streaming file reading module, such as [glob-stream](https://www.npmjs.com/package/glob-stream).

**Comment by przemyslawpluta** [comment]
Thanks @darsain will give it a go ... it's a flat directory so `recursive` is a default false but it looks like I have to `stat` files to figure out last 24h anyway. Can you choose which files have to be `stat`? From all the files I just need to `stat` one in five files with known extension?

e.g. there is a mix of video, audio and data files and the only files I have to stat are video files so list of extensions could be added as `fs.listAll(dir, [options], [callback]);`

**Comment by przemyslawpluta** [comment]
@darsain got an error when running `fs.listAll('mypath', callback)` agains the massive directory:

``` batch
path.js:405
    outputParts = outputParts.concat(toParts.slice(samePartsLength));
                                             ^
RangeError: Maximum call stack size exceeded
```

**Comment by darsain** [comment]
Oh, right, you are filling up the call stack. JavaScript doesn't have tail call optimization yet :/ and I don't feel like rewriting the logic into thunks and trampolines. Tail call optimization is part of ES 2015 (ES6), but dunno when that's gonna land in node. Soon(tm) I guess.

Meanwhile I suggest looking for a different module. This one is broken for this use case.

**Comment by przemyslawpluta** [comment]
OK ... with `glob-stream` I'm getting the list of all the files and obviously I need to `stats` files on my own.
So to list only the files `~1k files in 81ms` and `~22k files in 3432ms`.
