### ISSUE TITLE
fs-extended reading from mount issue

### ISSUE THREAD

**Issue by przemyslawpluta** [darsain/fs-extended#4]
Was using `fs-extended` for list all the files in the directory - network mount. The mount directory was renamed at source producing different list of files but `fs-extended` was still listing old files?

**Comment by darsain** [comment]
No idea. Not enough info.

And this module is deprecated. Use something like glob, glob-stream, or other recursive file listing module on npm.

**Comment by przemyslawpluta** [comment]
Thanks @darsain
